function xyz = rotatez(xyz0,S)
% rotatez(x0,y0,z0,S) - rotates 3D vector by angle S in radians about Z
%                       axis in a right hand system
xyz=[xyz0(1)*cos(S) - xyz0(2)*sin(S);...
    xyz0(1)*sin(S) + xyz0(2)*cos(S);...
    xyz0(3)];